### ISSUE TITLE
map not working

### ISSUE THREAD

**Issue by bigman224** [Luxaite-Network/Issue-Tracker#1]
### Expected Behavior

the map to work :(

### Actual Behavior

CModelLoader::Map_IsValid:  No such map 'maps/rp_downtown_tits_v2.bsp'
map load failed: rp_downtown_tits_v2 not found or invalid

### Reproduction Steps

```markdown
1.start the server
2.
3.
```

### Additional Information

pls help daddy**0w0**

**Comment by bigman224** [comment]
map is still in the workshop pack but shit still broke :(

**Comment by Aevoaa** [comment]
Solved
